# Generated by Django 5.0.6 on 2024-07-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="dst_ip",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="host",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="mail_activity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="msgid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="pid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="request_details",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="response_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="severity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="src_ip",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logfile",
            name="log_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apache", "Apache"),
                    ("sendmail", "Sendmail"),
                    ("ssl", "SSL"),
                    ("access", "Access"),
                    ("kernel", "Kernel"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
