# Generated by Django 5.0.6 on 2024-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_logentry_dst_ip_logentry_host_logentry_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="host",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
